version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      groups:
        safe-dependencies:
          update-types: ['minor', 'patch']
        major-dependencies:
          update-types: ['major']
